---
name: concourse

director_uuid: (( merge ))

releases:
  - name: concourse
    version: latest

jobs:
  - name: web
    instances: 1
    templates:
      - name: glider
        release: concourse
      - name: consul-agent
        release: concourse
    resource_pool: concourse
    persistent_disk: 1024 # for consul
    networks:
      - name: concourse
        static_ips: [10.244.8.2]
    properties:
      network_name: concourse
      consul:
        agent:
          mode: server
          services:
            - name: glider

  - name: worker
    instances: 1
    templates:
      - name: turbine
        release: concourse
      - name: warden
        release: concourse
      - name: consul-agent
        release: concourse
    resource_pool: concourse
    networks:
      - name: concourse
    properties:
      network_name: concourse
      consul:
        agent:
          servers:
            lan: [10.244.8.2]
          services:
            - name: turbine

networks:
  - name: concourse
    subnets:
      # network with static ip used for web
      - range: 10.244.8.0/30
        reserved: [10.244.8.1]
        static: [10.244.8.2]
        cloud_properties:
          name: random

      # networks for dynamic ips (db, workers, compilation vms)
      - range: 10.244.8.4/30
        reserved: [10.244.8.5]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.8.8/30
        reserved: [10.244.8.9]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.8.12/30
        reserved: [10.244.8.13]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.8.16/30
        reserved: [10.244.8.17]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.8.20/30
        reserved: [10.244.8.21]
        static: []
        cloud_properties:
          name: random

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: concourse
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
